import { Exercise } from "assets/Types";

export const EXERCISES: Exercise[] = [
  // CHEST
  {
    id: "pushups",
    name: "Push-ups",
    muscle: "Chest",
    modality: "calisthenics",
    estMinutes: 8,
    intensity: 2,
    equipment: "none",
    icon: "🤸",
  },
  {
    id: "incline_pushups",
    name: "Incline Push-ups",
    muscle: "Chest",
    modality: "calisthenics",
    estMinutes: 7,
    intensity: 1,
    equipment: "none",
  },
  {
    id: "bench_press",
    name: "Bench Press",
    muscle: "Chest",
    modality: "muscu",
    estMinutes: 12,
    intensity: 3,
    equipment: "gym",
    icon: "🏋️",
  },
  {
    id: "db_flyes",
    name: "Dumbbell Flyes",
    muscle: "Chest",
    modality: "muscu",
    estMinutes: 10,
    intensity: 2,
    equipment: "gym",
  },
  {
    id: "db_press",
    name: "Dumbbell Press",
    muscle: "Chest",
    modality: "muscu",
    estMinutes: 10,
    intensity: 2,
    equipment: "gym",
  },

  // BACK
  {
    id: "pullups",
    name: "Pull-ups",
    muscle: "Back",
    modality: "calisthenics",
    estMinutes: 10,
    intensity: 3,
    equipment: "basic",
    icon: "🧗",
  },
  {
    id: "inverted_row",
    name: "Inverted Rows",
    muscle: "Back",
    modality: "calisthenics",
    estMinutes: 9,
    intensity: 2,
    equipment: "basic",
  },
  {
    id: "lat_pulldown",
    name: "Lat Pulldown",
    muscle: "Back",
    modality: "muscu",
    estMinutes: 10,
    intensity: 2,
    equipment: "gym",
  },
  {
    id: "barbell_row",
    name: "Barbell Row",
    muscle: "Back",
    modality: "muscu",
    estMinutes: 12,
    intensity: 3,
    equipment: "gym",
  },
  {
    id: "seated_row",
    name: "Seated Cable Row",
    muscle: "Back",
    modality: "muscu",
    estMinutes: 10,
    intensity: 2,
    equipment: "gym",
  },

  // LEGS
  {
    id: "body_squats",
    name: "Bodyweight Squats",
    muscle: "Legs",
    modality: "calisthenics",
    estMinutes: 8,
    intensity: 2,
    equipment: "none",
  },
  {
    id: "lunges",
    name: "Lunges",
    muscle: "Legs",
    modality: "calisthenics",
    estMinutes: 9,
    intensity: 2,
    equipment: "none",
  },
  {
    id: "stepups",
    name: "Step-ups",
    muscle: "Legs",
    modality: "calisthenics",
    estMinutes: 9,
    intensity: 2,
    equipment: "basic",
  },
  {
    id: "back_squat",
    name: "Back Squat",
    muscle: "Legs",
    modality: "muscu",
    estMinutes: 14,
    intensity: 3,
    equipment: "gym",
  },
  {
    id: "romanian_dl",
    name: "Romanian Deadlift",
    muscle: "Legs",
    modality: "muscu",
    estMinutes: 12,
    intensity: 3,
    equipment: "gym",
  },
  {
    id: "leg_press",
    name: "Leg Press",
    muscle: "Legs",
    modality: "muscu",
    estMinutes: 10,
    intensity: 2,
    equipment: "gym",
  },

  // SHOULDERS
  {
    id: "pike_pushups",
    name: "Pike Push-ups",
    muscle: "Shoulders",
    modality: "calisthenics",
    estMinutes: 8,
    intensity: 2,
    equipment: "none",
  },
  {
    id: "handstand_hold",
    name: "Wall Handstand Hold",
    muscle: "Shoulders",
    modality: "calisthenics",
    estMinutes: 7,
    intensity: 2,
    equipment: "basic",
  },
  {
    id: "oh_press",
    name: "Overhead Press",
    muscle: "Shoulders",
    modality: "muscu",
    estMinutes: 12,
    intensity: 3,
    equipment: "gym",
  },
  {
    id: "lateral_raise",
    name: "Dumbbell Lateral Raise",
    muscle: "Shoulders",
    modality: "muscu",
    estMinutes: 8,
    intensity: 1,
    equipment: "gym",
  },
  {
    id: "rear_delt_fly",
    name: "Rear Delt Fly",
    muscle: "Shoulders",
    modality: "muscu",
    estMinutes: 8,
    intensity: 1,
    equipment: "gym",
  },

  // ARMS
  {
    id: "diamond_pushups",
    name: "Diamond Push-ups",
    muscle: "Arms",
    modality: "calisthenics",
    estMinutes: 8,
    intensity: 2,
    equipment: "none",
  },
  {
    id: "bench_dips",
    name: "Bench Dips",
    muscle: "Arms",
    modality: "calisthenics",
    estMinutes: 8,
    intensity: 2,
    equipment: "basic",
  },
  {
    id: "bb_curl",
    name: "Barbell Curl",
    muscle: "Arms",
    modality: "muscu",
    estMinutes: 8,
    intensity: 2,
    equipment: "gym",
  },
  {
    id: "db_curl",
    name: "Dumbbell Curl",
    muscle: "Arms",
    modality: "muscu",
    estMinutes: 8,
    intensity: 1,
    equipment: "gym",
  },
  {
    id: "tricep_pushdown",
    name: "Triceps Pushdown",
    muscle: "Arms",
    modality: "muscu",
    estMinutes: 8,
    intensity: 2,
    equipment: "gym",
  },

  // CORE
  {
    id: "plank",
    name: "Plank",
    muscle: "Core",
    modality: "both",
    estMinutes: 6,
    intensity: 1,
    equipment: "none",
  },
  {
    id: "hollow_hold",
    name: "Hollow Hold",
    muscle: "Core",
    modality: "calisthenics",
    estMinutes: 6,
    intensity: 2,
    equipment: "none",
  },
  {
    id: "hanging_knees",
    name: "Hanging Knee Raises",
    muscle: "Core",
    modality: "calisthenics",
    estMinutes: 9,
    intensity: 2,
    equipment: "basic",
  },
  {
    id: "cable_crunch",
    name: "Cable Crunch",
    muscle: "Core",
    modality: "muscu",
    estMinutes: 8,
    intensity: 2,
    equipment: "gym",
  },
  {
    id: "ab_wheel",
    name: "Ab Wheel Rollout",
    muscle: "Core",
    modality: "calisthenics",
    estMinutes: 8,
    intensity: 2,
    equipment: "basic",
  },

  // MIX (both / cardio strength blend)
  {
    id: "burpees",
    name: "Burpees",
    muscle: "Full Body" as any,
    modality: "calisthenics",
    estMinutes: 8,
    intensity: 3,
    equipment: "none",
  },
  {
    id: "kb_swing",
    name: "Kettlebell Swing",
    muscle: "Legs",
    modality: "muscu",
    estMinutes: 8,
    intensity: 2,
    equipment: "basic",
  },
  {
    id: "farmer_walk",
    name: "Farmer's Walk",
    muscle: "Back",
    modality: "muscu",
    estMinutes: 8,
    intensity: 2,
    equipment: "basic",
  },
  {
    id: "sled_push",
    name: "Sled Push",
    muscle: "Legs",
    modality: "muscu",
    estMinutes: 10,
    intensity: 3,
    equipment: "gym",
  },
  {
    id: "russian_twist",
    name: "Russian Twists",
    muscle: "Core",
    modality: "both",
    estMinutes: 6,
    intensity: 1,
    equipment: "none",
  },
  {
    id: "face_pull",
    name: "Face Pull",
    muscle: "Shoulders",
    modality: "muscu",
    estMinutes: 8,
    intensity: 1,
    equipment: "gym",
  },
  {
    id: "closegrip_bp",
    name: "Close-Grip Bench",
    muscle: "Arms",
    modality: "muscu",
    estMinutes: 10,
    intensity: 3,
    equipment: "gym",
  },
  {
    id: "chinups",
    name: "Chin-ups",
    muscle: "Arms",
    modality: "calisthenics",
    estMinutes: 10,
    intensity: 3,
    equipment: "basic",
  },
  {
    id: "hip_thrust",
    name: "Hip Thrust",
    muscle: "Legs",
    modality: "muscu",
    estMinutes: 10,
    intensity: 2,
    equipment: "gym",
  },
  {
    id: "good_morning",
    name: "Good Morning",
    muscle: "Back",
    modality: "muscu",
    estMinutes: 9,
    intensity: 2,
    equipment: "gym",
  },
];
