import { Exercise } from "assets/Types";

export const EXERCISES: Exercise[] = [
  // CHEST
  {
    id: "pushups",
    name: "Push-ups",
    muscle: "Upper Chest",
    modality: "calisthenics",
    estMinutes: 8,
    intensity: 2,
    equipment: "none",
  },
  {
    id: "incline_pushups",
    name: "Incline Push-ups",
    muscle: "Upper Chest",
    modality: "calisthenics",
    estMinutes: 7,
    intensity: 1,
    equipment: "none",
  },
  {
    id: "bench_press",
    name: "Bench Press",
    muscle: "Lower Chest",
    modality: "weight lifting",
    estMinutes: 12,
    intensity: 3,
    equipment: "gym",
  },
  {
    id: "db_press",
    name: "Dumbbell Press",
    muscle: "Lower Chest",
    modality: "weight lifting",
    estMinutes: 10,
    intensity: 2,
    equipment: "gym",
  },
  {
    id: "chest_dips",
    name: "Chest Dips",
    muscle: "Lower Chest",
    modality: "calisthenics",
    estMinutes: 9,
    intensity: 3,
    equipment: "basic",
  },
  {
    id: "incline_db_press",
    name: "Incline Dumbbell Press",
    muscle: "Upper Chest",
    modality: "weight lifting",
    estMinutes: 11,
    intensity: 3,
    equipment: "gym",
  },
  {
    id: "cable_fly",
    name: "Cable Fly",
    muscle: "Upper Chest",
    modality: "weight lifting",
    estMinutes: 9,
    intensity: 2,
    equipment: "gym",
  },

  // BACK
  {
    id: "pullups",
    name: "Pull-ups",
    muscle: "Lats",
    modality: "calisthenics",
    estMinutes: 10,
    intensity: 3,
    equipment: "basic",
  },
  {
    id: "inverted_row",
    name: "Inverted Rows",
    muscle: "Upper Back",
    modality: "calisthenics",
    estMinutes: 9,
    intensity: 2,
    equipment: "basic",
  },
  {
    id: "lat_pulldown",
    name: "Lat Pulldown",
    muscle: "Lats",
    modality: "weight lifting",
    estMinutes: 10,
    intensity: 2,
    equipment: "gym",
  },
  {
    id: "barbell_row",
    name: "Barbell Row",
    muscle: "Upper Back",
    modality: "weight lifting",
    estMinutes: 12,
    intensity: 3,
    equipment: "gym",
  },
  {
    id: "seated_row",
    name: "Seated Cable Row",
    muscle: "Upper Back",
    modality: "weight lifting",
    estMinutes: 10,
    intensity: 2,
    equipment: "gym",
  },
  {
    id: "deadlift",
    name: "Conventional Deadlift",
    muscle: "Lower Back",
    modality: "weight lifting",
    estMinutes: 14,
    intensity: 3,
    equipment: "gym",
  },

  // LEGS
  {
    id: "body_squats",
    name: "Bodyweight Squats",
    muscle: "Quads",
    modality: "calisthenics",
    estMinutes: 8,
    intensity: 2,
    equipment: "none",
  },
  {
    id: "lunges",
    name: "Lunges",
    muscle: "Quads",
    modality: "calisthenics",
    estMinutes: 9,
    intensity: 2,
    equipment: "none",
  },
  {
    id: "back_squat",
    name: "Back Squat",
    muscle: "Quads",
    modality: "weight lifting",
    estMinutes: 14,
    intensity: 3,
    equipment: "gym",
  },
  {
    id: "romanian_dl",
    name: "Romanian Deadlift",
    muscle: "Hamstrings",
    modality: "weight lifting",
    estMinutes: 12,
    intensity: 3,
    equipment: "gym",
  },
  {
    id: "leg_press",
    name: "Leg Press",
    muscle: "Quads",
    modality: "weight lifting",
    estMinutes: 10,
    intensity: 2,
    equipment: "gym",
  },
  {
    id: "front_squat",
    name: "Front Squat",
    muscle: "Quads",
    modality: "weight lifting",
    estMinutes: 13,
    intensity: 3,
    equipment: "gym",
  },
  {
    id: "walking_lunges",
    name: "Walking Lunges",
    muscle: "Quads",
    modality: "both",
    estMinutes: 9,
    intensity: 2,
    equipment: "basic",
  },
  {
    id: "hip_thrust",
    name: "Hip Thrust",
    muscle: "Hamstrings",
    modality: "weight lifting",
    estMinutes: 10,
    intensity: 2,
    equipment: "gym",
  },

  // CALVES
  {
    id: "standing_calf_raise",
    name: "Standing Calf Raise",
    muscle: "Calves",
    modality: "calisthenics",
    estMinutes: 6,
    intensity: 1,
    equipment: "none",
  },
  {
    id: "seated_calf_raise",
    name: "Seated Calf Raise",
    muscle: "Calves",
    modality: "weight lifting",
    estMinutes: 7,
    intensity: 2,
    equipment: "gym",
  },

  // SHOULDERS
  {
    id: "pike_pushups",
    name: "Pike Push-ups",
    muscle: "Front Deltoid",
    modality: "calisthenics",
    estMinutes: 8,
    intensity: 2,
    equipment: "none",
  },
  {
    id: "oh_press",
    name: "Overhead Press",
    muscle: "Front Deltoid",
    modality: "weight lifting",
    estMinutes: 12,
    intensity: 3,
    equipment: "gym",
  },
  {
    id: "lateral_raise",
    name: "Dumbbell Lateral Raise",
    muscle: "Lateral Deltoid",
    modality: "weight lifting",
    estMinutes: 8,
    intensity: 1,
    equipment: "gym",
  },
  {
    id: "rear_delt_fly",
    name: "Rear Delt Fly",
    muscle: "Rear Deltoid",
    modality: "weight lifting",
    estMinutes: 8,
    intensity: 1,
    equipment: "gym",
  },
  {
    id: "arnold_press",
    name: "Arnold Press",
    muscle: "Front Deltoid",
    modality: "weight lifting",
    estMinutes: 11,
    intensity: 3,
    equipment: "gym",
  },
  {
    id: "upright_row",
    name: "Upright Row",
    muscle: "Lateral Deltoid",
    modality: "weight lifting",
    estMinutes: 9,
    intensity: 2,
    equipment: "gym",
  },
  {
    id: "face_pull",
    name: "Face Pull",
    muscle: "Rear Deltoid",
    modality: "weight lifting",
    estMinutes: 8,
    intensity: 1,
    equipment: "gym",
  },

  // BICEPS
  {
    id: "bb_curl",
    name: "Barbell Curl",
    muscle: "Biceps",
    modality: "weight lifting",
    estMinutes: 8,
    intensity: 2,
    equipment: "gym",
  },
  {
    id: "hammer_curl",
    name: "Hammer Curl",
    muscle: "Biceps",
    modality: "weight lifting",
    estMinutes: 8,
    intensity: 1,
    equipment: "gym",
  },

  // TRICEPS
  {
    id: "diamond_pushups",
    name: "Diamond Push-ups",
    muscle: "Triceps",
    modality: "calisthenics",
    estMinutes: 8,
    intensity: 2,
    equipment: "none",
  },
  {
    id: "bench_dips",
    name: "Bench Dips",
    muscle: "Triceps",
    modality: "calisthenics",
    estMinutes: 8,
    intensity: 2,
    equipment: "basic",
  },
  {
    id: "tricep_pushdown",
    name: "Triceps Pushdown",
    muscle: "Triceps",
    modality: "weight lifting",
    estMinutes: 8,
    intensity: 2,
    equipment: "gym",
  },
  {
    id: "skull_crusher",
    name: "Skull Crusher",
    muscle: "Triceps",
    modality: "weight lifting",
    estMinutes: 9,
    intensity: 2,
    equipment: "gym",
  },

  // FOREARMS
  {
    id: "wrist_curl",
    name: "Wrist Curl",
    muscle: "Forearms",
    modality: "weight lifting",
    estMinutes: 6,
    intensity: 1,
    equipment: "basic",
  },
  {
    id: "farmer_carry",
    name: "Farmer's Carry",
    muscle: "Forearms",
    modality: "weight lifting",
    estMinutes: 8,
    intensity: 2,
    equipment: "basic",
  },

  // CORE
  {
    id: "plank",
    name: "Plank",
    muscle: "Core",
    modality: "calisthenics",
    estMinutes: 6,
    intensity: 1,
    equipment: "none",
  },
  {
    id: "hanging_knees",
    name: "Hanging Knee Raises",
    muscle: "Core",
    modality: "calisthenics",
    estMinutes: 9,
    intensity: 2,
    equipment: "basic",
  },
  {
    id: "cable_crunch",
    name: "Cable Crunch",
    muscle: "Core",
    modality: "weight lifting",
    estMinutes: 8,
    intensity: 2,
    equipment: "gym",
  },
  {
    id: "ab_wheel",
    name: "Ab Wheel Rollout",
    muscle: "Core",
    modality: "calisthenics",
    estMinutes: 8,
    intensity: 2,
    equipment: "basic",
  },
  {
    id: "bicycle_crunch",
    name: "Bicycle Crunch",
    muscle: "Core",
    modality: "calisthenics",
    estMinutes: 6,
    intensity: 1,
    equipment: "none",
  },
  {
    id: "v_ups",
    name: "V-Ups",
    muscle: "Core",
    modality: "calisthenics",
    estMinutes: 7,
    intensity: 2,
    equipment: "none",
  },
  {
    id: "side_plank",
    name: "Side Plank",
    muscle: "Core",
    modality: "calisthenics",
    estMinutes: 6,
    intensity: 1,
    equipment: "none",
  },

  // MIX
  {
    id: "burpees",
    name: "Burpees",
    muscle: "Full Body" as any,
    modality: "calisthenics",
    estMinutes: 8,
    intensity: 3,
    equipment: "none",
  },
  {
    id: "kb_swing",
    name: "Kettlebell Swing",
    muscle: "Hamstrings",
    modality: "weight lifting",
    estMinutes: 8,
    intensity: 2,
    equipment: "basic",
  },
  {
    id: "russian_twist",
    name: "Russian Twists",
    muscle: "Core",
    modality: "both",
    estMinutes: 6,
    intensity: 1,
    equipment: "none",
  },
];
